version: "3"
services: 
  quaver-api:
    build: .
    ports: 
      - 3000:3000
    environment: 
      - PORT=3000
      - MONGO_USER=quaver
      - MONGO_PASSWORD=quaver
      - SESSION_SECRET=quaver
    depends_on: 
      - mongo

  mongo:
    image: mongo
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=quaver
      - MONGO_INITDB_ROOT_PASSWORD=quaver