version: "3.4"
services: 
  quaver:
    build: 
      context: .
      network: host
    ports: 
      - 3000:3000
    volumes:
      - ./music/:/music
    environment: 
      - PORT=3000
      - MONGO_USER=quaver
      - MONGO_PASSWORD=quaver
      - SESSION_SECRET=quaver
      - MUSIC_PATH=/music
    depends_on: 
      - mongo

  mongo:
    image: mongo
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=quaver
      - MONGO_INITDB_ROOT_PASSWORD=quaver