version: "3.4"
services:
  quaver:
    build:
      context: .
      network: host
    ports:
      - 8080:8080
    volumes:
      - ./data/:/data
      - ./music/:/music
      - ./dist/src/:/app/src
    environment:
      - QUAVER_DB_USER=quaver
      - QUAVER_DB_PASSWORD=quaver
      - QUAVER_DEBUG_LEVEL=0
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=quaver
      - MONGO_INITDB_ROOT_PASSWORD=quaver

  mongoNew:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=quaver
      - MONGO_INITDB_ROOT_PASSWORD=quaver
