version: "3"
services: 
  quaver:
    build: .
    ports: 
      - 3000:3000
    environment: 
      - PORT=3000

  mongo:
    image: mongo
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=quaver
      - MONGO_INITDB_ROOT_PASSWORD=quaver