name: Docker Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Build Quaver
      run: npm run build
    - 
      name: Build the Docker image
      run: docker build . --file Dockerfile --tag quaver-test
